welcome:
    resource: "@WelcomeBundle/Resources/config/routing.yml"
    prefix:   /

moves:
    resource: "@MovesBundle/Resources/config/routing.yml"
    prefix:   /moves

home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /home

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
    
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

moves_login:
    path: /login/check-moves