welcome:
    resource: "@WelcomeBundle/Resources/config/routing.yml"
    prefix:   /

moves:
    resource: "@MovesBundle/Resources/config/routing.yml"
    prefix:   /moves

home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /home

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
