# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#moves_user_provider.class: AppBundle\Security\Core\User\FOSUBUserProvider

services:
    moves_user_provider:
        class:        AppBundle\Security\Core\User\MyFOSUBUserProvider
        arguments: ['@fos_user.user_manager', { moves: moves_id }]